---
title: "DT4F"
author: "Kun Zhang, Ziyun Ni, Ruixuan Zhou, Kevin Hardegger"
date: "1 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(warning = FALSE)

# loading libraries
library(xts)
library(PerformanceAnalytics)
library(psych)
library(rollRegres)
library(roll)

# load csv file prices
prices <- read.table("StockPricesDaily.csv",sep = ";", header = TRUE, na = "NA")
date <- as.Date(prices[,1],format="%d.%m.%Y")

prices.ts <- xts(x = prices[,-1], order.by = date)
returns <- Return.calculate(prices = prices.ts, method = 'discrete')

# load csv file betas
Daily_betas <- read.table("Stock_betas_daily.csv",sep = ";", header = TRUE, na = "NA")
date_betas <- as.Date(Daily_betas[,1],format="%d.%m.%Y")
Daily_betas <- xts(x = Daily_betas[,-1], order.by = date_betas)

Daily_betas.ts <- as.matrix(Daily_betas['1994-04-29/2017-12-28'])

Daily_Returns <- as.matrix(returns['1994-04-30/2017-12-29'])
```

```{r, Building Portfolios}
# create empty vectors with length = number of periods
P_Returns_P1_daily <- as.matrix(rep(NA,dim(Daily_betas.ts)[1]))
P_Returns_P2_daily <- as.matrix(rep(NA,dim(Daily_betas.ts)[1]))
P_Returns_P3_daily <- as.matrix(rep(NA,dim(Daily_betas.ts)[1]))
P_Returns_P4_daily <- as.matrix(rep(NA,dim(Daily_betas.ts)[1]))
P_Returns_P5_daily <- as.matrix(rep(NA,dim(Daily_betas.ts)[1]))
```

```{r, Calculating Returns}
# use a for loop to go through each time period

for (j in 1:dim(Daily_betas.ts)[1])
{
  
  SUB_daily <- Daily_betas.ts[j,]
  
  # divide the stocks contained in SMI into 5 portfolios based on their betas
  
  P1_P_daily <- subset(SUB_daily,subset = SUB_daily < quantile(SUB_daily , c(0.2),na.rm=TRUE))
  P2_P_daily <- subset(SUB_daily,subset = SUB_daily < quantile(SUB_daily , c(0.4),na.rm=TRUE)& SUB_daily >= quantile(SUB_daily , c(0.2),na.rm=TRUE))
  P3_P_daily <- subset(SUB_daily,subset = SUB_daily < quantile(SUB_daily , c(0.6),na.rm=TRUE)& SUB_daily >= quantile(SUB_daily , c(0.4),na.rm=TRUE))
  P4_P_daily <- subset(SUB_daily,subset = SUB_daily < quantile(SUB_daily , c(0.8),na.rm=TRUE)& SUB_daily >= quantile(SUB_daily , c(0.6),na.rm=TRUE))
  P5_P_daily <- subset(SUB_daily,subset = SUB_daily >= quantile(SUB_daily, c(0.8),na.rm=TRUE))
  
  # calculate the returns of the portfolios of each beta ranked portfolios for every single period
  
  P_Returns_P1_daily[j] <- mean(Daily_Returns[j,names(P1_P_daily)],na.rm=TRUE)
  P_Returns_P2_daily[j] <- mean(Daily_Returns[j,names(P2_P_daily)],na.rm=TRUE)
  P_Returns_P3_daily[j] <- mean(Daily_Returns[j,names(P3_P_daily)],na.rm=TRUE)
  P_Returns_P4_daily[j] <- mean(Daily_Returns[j,names(P4_P_daily)],na.rm=TRUE)
  P_Returns_P5_daily[j] <- mean(Daily_Returns[j,names(P5_P_daily)],na.rm=TRUE)
}

# calculate the mean returns of the five beta-sorted portfolios 

print(mean_return_P1<-mean(P_Returns_P1_daily,na.rm=TRUE))
print(mean_return_P2<-mean(P_Returns_P2_daily,na.rm=TRUE))
print(mean_return_P3<-mean(P_Returns_P3_daily,na.rm=TRUE))
print(mean_return_P4<-mean(P_Returns_P4_daily,na.rm=TRUE))
print(mean_return_P5<-mean(P_Returns_P5_daily,na.rm=TRUE))

# calculated the mean standard deviation of the five beta-sorted portfolios
print(sd_P1<-sd(P_Returns_P1_daily,na.rm=TRUE))
print(sd_P2<-sd(P_Returns_P2_daily,na.rm=TRUE))
print(sd_P3<-sd(P_Returns_P3_daily,na.rm=TRUE))
print(sd_P4<-sd(P_Returns_P4_daily,na.rm=TRUE))
print(sd_P5<-sd(P_Returns_P5_daily,na.rm=TRUE))
```

```{r, Plotting Results}
# plot results
# calculate cumulative returns of each portfolio
cumulative_returns_p1_monthly <- cumprod(1+P_Returns_P1_daily)
cumulative_returns_p2_monthly <- cumprod(1+P_Returns_P2_daily)
cumulative_returns_p3_monthly <- cumprod(1+P_Returns_P3_daily)
cumulative_returns_p4_monthly <- cumprod(1+P_Returns_P4_daily)
cumulative_returns_p5_monthly <- cumprod(1+P_Returns_P5_daily)

# draw the plot
plot(x=date_betas[2:6176], y=cumulative_returns_p1_monthly, ylim=c(0,16),type= "l", lty = 1, lwd = 3, col = "yellow", cex.axis = 1, cex.lab = 1, ylab = "Cumulative Return", xlab = "Time")
lines(date_betas[2:6176], cumulative_returns_p2_monthly, lty = 3, lwd = 3, col = "blue")
lines(date_betas[2:6176], cumulative_returns_p3_monthly, lty = 4, lwd = 3, col = "gray")
lines(date_betas[2:6176], cumulative_returns_p4_monthly, lty = 2, lwd = 3, col = "red")
lines(date_betas[2:6176], cumulative_returns_p5_monthly, lty = 1, lwd = 3, col = "black")
legend("topleft", c("Portfolio 1", "Portfolio 2", "Portfolio 3", "Portfolio 4", "Portfolio 5"), 
       lty = c(1,3,4,2,1), lwd = 3, bty = "n",cex = 1.2, col = c("yellow", "blue", "gray","red","black"))

```

